# Generated by Django 5.2.8 on 2025-12-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="height",
            field=models.PositiveIntegerField(
                default=1, help_text="Product height in cm"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="length",
            field=models.PositiveIntegerField(
                default=1, help_text="Product length in cm"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="variant_name",
            field=models.CharField(default="nothing", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="width",
            field=models.PositiveIntegerField(
                default=1, help_text="Product width in cm"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.PositiveIntegerField(help_text="Product weight in grams"),
        ),
    ]
