# Generated by Django 5.2.8 on 2025-12-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShippingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                ("province_id_ro", models.IntegerField()),
                ("city_id_ro", models.IntegerField()),
                ("district_id_ro", models.IntegerField()),
                ("street_address", models.CharField(max_length=255)),
                ("postal_code", models.IntegerField()),
            ],
            options={
                "unique_together": {
                    (
                        "province_id_ro",
                        "city_id_ro",
                        "district_id_ro",
                        "street_address",
                        "postal_code",
                    )
                },
            },
        ),
    ]
