# Generated by Django 5.2.8 on 2025-12-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_address", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shippingaddress",
            unique_together={
                ("province", "city", "district", "subdistrict", "street_address")
            },
        ),
        migrations.AddField(
            model_name="subdistrict",
            name="zip_code",
            field=models.CharField(max_length=10),
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="postal_code",
        ),
    ]
